### ISSUE TITLE
Docs don't explain how to run tests

### ISSUE THREAD

**Issue by yurivict** [althonos/pyrodigal#25]
[here](https://pyrodigal.readthedocs.io/en/stable/install.html)

I tried to run pytest from the project directory, but got:
```
collected 0 items / 9 errors                                                                                                                                                                 

=========================================================================================== ERRORS ===========================================================================================
_________________________________________________________________ ERROR collecting pyrodigal/tests/test_connection_scorer.py _________________________________________________________________
ImportError while importing test module '/disk-samsung/freebsd-ports/biology/py-pyrodigal/work-py39/pyrodigal-2.0.2/pyrodigal/tests/test_connection_scorer.py'.
Hint: make sure your test modules/packages have valid Python names.
Traceback:
/usr/local/lib/python3.9/importlib/__init__.py:127: in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
pyrodigal/__init__.py:8: in <module>
    from . import _pyrodigal
E   ImportError: cannot import name '_pyrodigal' from partially initialized module 'pyrodigal' (most likely due to a circular import) (/disk-samsung/freebsd-ports/biology/py-pyrodigal/work-py39/pyrodigal-2.0.2/pyrodigal/__init__.py)
______________________________________________________________________ ERROR collecting pyrodigal/tests/test_doctest.py ______________________________________________________________________
ImportError while importing test module '/disk-samsung/freebsd-ports/biology/py-pyrodigal/work-py39/pyrodigal-2.0.2/pyrodigal/tests/test_doctest.py'.
Hint: make sure your test modules/packages have valid Python names.
Traceback:
/usr/local/lib/python3.9/importlib/__init__.py:127: in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
pyrodigal/__init__.py:8: in <module>
    from . import _pyrodigal
E   ImportError: cannot import name '_pyrodigal' from partially initialized module 'pyrodigal' (most likely due to a circular import) (/disk-samsung/freebsd-ports/biology/py-pyrodigal/work-py39/pyrodigal-2.0.2/pyrodigal/__init__.py)
_______________________________________________________________________ ERROR collecting pyrodigal/tests/test_gene.py ________________________________________________________________________
ImportError while importing test module '/disk-samsung/freebsd-ports/biology/py-pyrodigal/work-py39/pyrodigal-2.0.2/pyrodigal/tests/test_gene.py'.
Hint: make sure your test modules/packages have valid Python names.
Traceback:
/usr/local/lib/python3.9/importlib/__init__.py:127: in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
pyrodigal/__init__.py:8: in <module>
    from . import _pyrodigal
E   ImportError: cannot import name '_pyrodigal' from partially initialized module 'pyrodigal' (most likely due to a circular import) (/disk-samsung/freebsd-ports/biology/py-pyrodigal/work-py39/pyrodigal-2.0.2/pyrodigal/__init__.py)
_______________________________________________________________________ ERROR collecting pyrodigal/tests/test_genes.py _______________________________________________________________________
ImportError while importing test module '/disk-samsung/freebsd-ports/biology/py-pyrodigal/work-py39/pyrodigal-2.0.2/pyrodigal/tests/test_genes.py'.
Hint: make sure your test modules/packages have valid Python names.
Traceback:
/usr/local/lib/python3.9/importlib/__init__.py:127: in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
pyrodigal/__init__.py:8: in <module>
    from . import _pyrodigal
E   ImportError: cannot import name '_pyrodigal' from partially initialized module 'pyrodigal' (most likely due to a circular import) (/disk-samsung/freebsd-ports/biology/py-pyrodigal/work-py39/pyrodigal-2.0.2/pyrodigal/__init__.py)
_______________________________________________________________________ ERROR collecting pyrodigal/tests/test_mask.py ________________________________________________________________________
ImportError while importing test module '/disk-samsung/freebsd-ports/biology/py-pyrodigal/work-py39/pyrodigal-2.0.2/pyrodigal/tests/test_mask.py'.
Hint: make sure your test modules/packages have valid Python names.
Traceback:
/usr/local/lib/python3.9/importlib/__init__.py:127: in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
pyrodigal/__init__.py:8: in <module>
    from . import _pyrodigal
E   ImportError: cannot import name '_pyrodigal' from partially initialized module 'pyrodigal' (most likely due to a circular import) (/disk-samsung/freebsd-ports/biology/py-pyrodigal/work-py39/pyrodigal-2.0.2/pyrodigal/__init__.py)
_______________________________________________________________________ ERROR collecting pyrodigal/tests/test_nodes.py _______________________________________________________________________
ImportError while importing test module '/disk-samsung/freebsd-ports/biology/py-pyrodigal/work-py39/pyrodigal-2.0.2/pyrodigal/tests/test_nodes.py'.
Hint: make sure your test modules/packages have valid Python names.
Traceback:
/usr/local/lib/python3.9/importlib/__init__.py:127: in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
pyrodigal/__init__.py:8: in <module>
    from . import _pyrodigal
E   ImportError: cannot import name '_pyrodigal' from partially initialized module 'pyrodigal' (most likely due to a circular import) (/disk-samsung/freebsd-ports/biology/py-pyrodigal/work-py39/pyrodigal-2.0.2/pyrodigal/__init__.py)
____________________________________________________________________ ERROR collecting pyrodigal/tests/test_orf_finder.py _____________________________________________________________________
ImportError while importing test module '/disk-samsung/freebsd-ports/biology/py-pyrodigal/work-py39/pyrodigal-2.0.2/pyrodigal/tests/test_orf_finder.py'.
Hint: make sure your test modules/packages have valid Python names.
Traceback:
/usr/local/lib/python3.9/importlib/__init__.py:127: in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
pyrodigal/__init__.py:8: in <module>
    from . import _pyrodigal
E   ImportError: cannot import name '_pyrodigal' from partially initialized module 'pyrodigal' (most likely due to a circular import) (/disk-samsung/freebsd-ports/biology/py-pyrodigal/work-py39/pyrodigal-2.0.2/pyrodigal/__init__.py)
```

Python-3.9
FreeBSD 13.1

**Comment by althonos** [comment]
Yes they do, in the contribution guide: https://pyrodigal.readthedocs.io/en/stable/contributing.html

**Comment by yurivict** [comment]
The command recommended there fails in a similar fashion:
```
cd /disk-samsung/freebsd-ports/biology/py-pyrodigal/work-py39/pyrodigal-2.0.2 && /usr/bin/env XDG_DATA_HOME=/disk-samsung/freebsd-ports/biology/py-pyrodigal/work-py39  XDG_CONFIG_HOME=/disk-samsung/freebsd-ports/biology/py-pyrodigal/work-py39  XDG_CACHE_HOME=/disk-samsung/freebsd-ports/biology/py-pyrodigal/work-py39/.cache  HOME=/disk-samsung/freebsd-ports/biology/py-pyrodigal/work-py39 PATH=/usr/local/libexec/ccache:/disk-samsung/freebsd-ports/biology/py-pyrodigal/work-py39/.bin:/home/yuri/bin:/sbin:/bin:/usr/sbin:/usr/bin:/usr/local/sbin:/usr/local/bin PKG_CONFIG_LIBDIR=/disk-samsung/freebsd-ports/biology/py-pyrodigal/work-py39/.pkgconfig:/usr/local/libdata/pkgconfig:/usr/local/share/pkgconfig:/usr/libdata/pkgconfig MK_DEBUG_FILES=no MK_KERNEL_SYMBOLS=no SHELL=/bin/sh NO_LINT=YES LDSHARED="cc -shared" PYTHONDONTWRITEBYTECODE= PYTHONOPTIMIZE= PREFIX=/usr/local  LOCALBASE=/usr/local  CC="cc" CFLAGS="-O2 -pipe  -fstack-protector-strong -fno-strict-aliasing "  CPP="cpp" CPPFLAGS=""  LDFLAGS=" -fstack-protector-strong " LIBS=""  CXX="c++" CXXFLAGS="-O2 -pipe -fstack-protector-strong -fno-strict-aliasing  "  MANPREFIX="/usr/local" CCACHE_DIR="/tmp/.ccache" BSD_INSTALL_PROGRAM="install  -s -m 555"  BSD_INSTALL_LIB="install  -s -m 0644"  BSD_INSTALL_SCRIPT="install  -m 555"  BSD_INSTALL_DATA="install  -m 0644"  BSD_INSTALL_MAN="install  -m 444" PYTHONPATH=/disk-samsung/freebsd-ports/biology/py-pyrodigal/work-py39/stage/usr/local/lib/python3.9/site-packages /usr/local/bin/python3.9 -m unittest discover -vv
pyrodigal (unittest.loader._FailedTest) ... ERROR

======================================================================
ERROR: pyrodigal (unittest.loader._FailedTest)
----------------------------------------------------------------------
ImportError: Failed to import test module: pyrodigal
Traceback (most recent call last):
  File "/usr/local/lib/python3.9/unittest/loader.py", line 470, in _find_test_path
    package = self._get_module_from_name(name)
  File "/usr/local/lib/python3.9/unittest/loader.py", line 377, in _get_module_from_name
    __import__(name)
  File "/disk-samsung/freebsd-ports/biology/py-pyrodigal/work-py39/pyrodigal-2.0.2/pyrodigal/__init__.py", line 8, in <module>
    from . import _pyrodigal
ImportError: cannot import name '_pyrodigal' from partially initialized module 'pyrodigal' (most likely due to a circular import) (/disk-samsung/freebsd-ports/biology/py-pyrodigal/work-py39/pyrodigal-2.0.2/pyrodigal/__init__.py)


----------------------------------------------------------------------
Ran 1 test in 0.001s

FAILED (errors=1)
*** Error code 1
```

**Comment by yurivict** [comment]
It works now.
Thank you.
